name: C/C++ CI

on:
  push:
    branches: [ "master", "workflows" ]
  pull_request:
    branches: [ "master", "workflows" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Eigen3
      run: sudo apt install -y libeigen3-dev
    - name: make
      run: cd cpp && mkdir build && cd build && cmake .. && make
    - name: tests
      run: cd cpp/build && ./unit_tests
